import { PO_LABELS } from '@/pages/purchase-orders/poTerminology';

/** Shared product field labels — keep in sync across sheet, form, and inventory. */
export const PRODUCT_FIELD_LABELS = {
  sku: 'SKU',
  name: 'Name',
  packQty: PO_LABELS.packQty,
  buyUom: PO_LABELS.buyUom,
  unitsPerPack: PO_LABELS.unitsPerPack,
  poUnitCost: PO_LABELS.unitCost,
  brand: 'Brand',
  country: 'Country',
  category: 'Category',
  barcode: 'Barcode',
  supplier: 'Supplier',
  baseUom: 'Secondary Unit',
  sellMode: 'Sell mode',
  unitCost: 'Unit cost',
  packCost: 'Pack cost',
  unitPrice: 'Unit price',
  packPrice: 'Pack price',
  marginPercent: 'Margin %',
  packSavings: 'Pack savings',
  discountPercent: 'Discount %',
  offeredPrice: 'Offered price',
  packDiscountPercent: 'Pack discount %',
  packOfferedPrice: 'Pack offered price',
  lowStock: 'Low stock',
  status: 'Status',
  tags: 'Tags',
  nutrition: 'Nutrition',
  allergens: 'Allergens',
  images: 'Images',
  stock: 'Stock',
  description: 'Description',
} as const;
